### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by tkz96**

### CODE REVIEW

**Comment by tkz96** [comment]
Hello Talha! Great job on your first project. Everything seems to be running well and there are plenty of things that are working just right.
👏 👏 👏 
There is just a little, teeny-tiny amount of work we need to do to take your project from good to awesome!

Please check out the comments that would really help you get going.

Good luck! 💪

**Comment by tkz96** [comment]
It would be a real help for you if you install the linters on your repository.
Linters help to prevent us from making mistakes and writing clean code and make our life so much better. 
If you need help, simply check out [how to set up linters](https://github.com/microverseinc/linters-config/tree/master/html-css).

**Comment by tkz96** [comment]
It is a great idea to always put the **script** tag in the **head** tag. Be sure to move it up.

`
  <body>
    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
    <h1 id="title">Microverse Survey Form</h1>
`

**Comment by tkz96** [comment]
Your web pages need some style. I think it will be great if you modify the styles.css file and make your form more visually appealing.

**Review by keroloussamy — APPROVED** [review]
Hi @tkz96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- Includes an explanation.✔️
- Comments are clear and easy to understand. ✔️

clap

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
